/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pappu_com_staticimageopengl_java_jni_Facedetection */

#ifndef _Included_pappu_com_staticimageopengl_java_jni_Facedetection
#define _Included_pappu_com_staticimageopengl_java_jni_Facedetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pappu_com_staticimageopengl_java_jni_Facedetection
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pappu_com_staticimageopengl_java_1jni_Facedetection_initialize
  (JNIEnv *, jobject);

/*
 * Class:     pappu_com_staticimageopengl_java_jni_Facedetection
 * Method:    getRectangle
 * Signature: (I)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pappu_com_staticimageopengl_java_1jni_Facedetection_getRectangle
  (JNIEnv *, jobject, jint);

/*
 * Class:     pappu_com_staticimageopengl_java_jni_Facedetection
 * Method:    deserialize
 * Signature: ([I[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_pappu_com_staticimageopengl_java_1jni_Facedetection_deserialize
  (JNIEnv *, jobject, jintArray, jobjectArray);

/*
 * Class:     pappu_com_staticimageopengl_java_jni_Facedetection
 * Method:    faceDetect
 * Signature: ([BJJIIZ)[I
 */
JNIEXPORT jintArray JNICALL Java_pappu_com_staticimageopengl_java_1jni_Facedetection_faceDetect
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jint, jint, jboolean);

/*
 * Class:     pappu_com_staticimageopengl_java_jni_Facedetection
 * Method:    detecttionOfGalleryImage
 * Signature: ([BJJ)V
 */
JNIEXPORT jintArray JNICALL Java_pappu_com_staticimageopengl_java_1jni_Facedetection_detecttionOfGalleryImage
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
